logging:
  level:
    root: warn
    org.springframework.web: debug

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
#        default_schema: search
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        # Enable second level cache
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#          provider_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#          ehcache:
#            configuration_resource_name: ehcache.xml
    open-in-view: false
