spring:
  jpa:
    hibernate:
      # ddl-auto: none
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    # url: jdbc:oracle:thin:@localhost:1521:orcl
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    # driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: org.h2.Driver
