
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?charSet=utf-8
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    root: debug
    org:
      springframework:
        boot.autoconfigure: info
        batch: trace
