logging:
  level:
    root: info
    com.demo: debug

# FeignGlobalConfig.java로 대체
# https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html
#feign:
#  client:
#    config:
#      default:
#        logger-level: full
#        read-timeout: 3_000
#        connect-timeout: 5_000
#        follow-redirects: true
