spring:
  datasource:
    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  # HMAC-SHA(HS)256 알고리즘을 사용할 경우 256 bits 이상의 Secret 필수
  secret: "123456789012345678901234567890123"
