spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:1521/querydsl
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # System.out?? Hibernate ?? SQL? ???.
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # logger? Hibernate ?? SQL? ???.
#  org.hibernate.type: trace # SQL ?? ????? ??? ???.
